// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlcVEYm7wMhN5XBSXoRGveU1fxU9M268',
    appId: '1:262285410223:android:7d41d22ecb1445aa25b95a',
    messagingSenderId: '262285410223',
    projectId: 'oneup-backend',
    databaseURL: 'https://oneup-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oneup-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9f1bEPmGUCr6A1Kpxc_wyLWGZvuGR9Co',
    appId: '1:262285410223:ios:8eb747d030dcd2fd25b95a',
    messagingSenderId: '262285410223',
    projectId: 'oneup-backend',
    databaseURL: 'https://oneup-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oneup-backend.firebasestorage.app',
    iosBundleId: 'com.oneup.sports.oneUpApp',
  );
}
